### PR TITLE
allow focuspoints on FileReference to be null, so that MetaData values can be loaded

### PR DESCRIPTION
**Pull request by yeldiRium**
Accompanying PullRequest for my suggested fix in [Issue 60](https://github.com/lochmueller/focuspoint/issues/40#issuecomment-415080815)

### CODE REVIEW

**Comment by yeldiRium** [comment]
The travis error seems temporary to me. @lochmueller can you please restart the build and check if it completes successfully the second time?

**Comment by lochmueller** [comment]
Patch looks good. I will check the Travis later. Thanks for the fix...

**Comment by yeldiRium** [comment]
It might still be necessary to set a default value in the TCA, so that new data points aren't created with zero values. I will check that tomorrow and update this PR if nessecary.

Thanks for the quick reaction!

**Comment by yeldiRium** [comment]
I checked and the values are set to null for new references. We are done here :)

**Pull request merged**
